### ISSUE TITLE
Initial test results

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/hero-display#1]
Today I tested this on Hero1. 
@LarsJanssenTUe forwarded me an `.AppImage`. On my own laptop that displays the given text as per the `README` :heavy_check_mark: 

However, on `hero1`, the executeable exits immediately without displaying anything. 
```bash
administrator@hero1 $ DISPLAY=:0 ./hero-display\ 0.0.1.AppImage 
Invalid MIT-MAGIC-COOKIE-1 key[~]
administrator@hero1 $ export DISPLAY=desktop:0
[~]
administrator@hero1 $ ./hero-display\ 0.0.1.AppImage 
[~]
```

It could be that I `export` the wrong display

**Comment by LoyVanBeek** [comment]
Aha, but it needs to be ran as `hsr-hmi` I think... I don't know the password though

**Comment by LoyVanBeek** [comment]
```bash
amigo@athome10 $ ssh administrator@hero1.local
Last login: Tue May 28 22:14:18 2019 from 192.168.44.103
[~]
administrator@hero1 $ sudo su - hsr-hmi
[sudo] password for administrator: 
Sorry, try again.
[sudo] password for administrator: 

hsr-hmi@hero1:~$ DISPLAY=:0 ./hero-display\ 0.0.1.AppImage
```

works

**Comment by LoyVanBeek** [comment]
Next issue: No output shown. 

When connecting, the websocket_bridge (that is already running) does correctly show the number of clients connected:
```bash
administrator@hero1 $ rostopic echo /hero/connected_clients
clients: []
---
clients: 
  - 
    ip_address: "127.0.0.1"
    connection_time: 
      secs: 1559076224
      nsecs: 587882995
---
```

but no output shown.

**Comment by reinzor** [comment]
https://github.com/tue-robotics/hero-display/blob/master/src/renderer/App.vue#L75 shows to what websocket it is connecting. Please verify that this is the websocket running on hero.

**Comment by LarsJanssenTUe** [comment]
So far it seems that the websockets are correctly linked (I think this is also supported by the fact that the screen on the robot also actually turns white), however when a message is published over /text_to_speech/output std_msgs/String there is no  subscriber to that node so the text that is published over that node does not show up on the screen.

**Comment by reinzor** [comment]
Did you try the example? For me this works:

![image](https://user-images.githubusercontent.com/4176023/58897933-c31dce80-86f9-11e9-8c8d-d12e3646ba9a.png)

**Comment by reinzor** [comment]
Does the rosbridge run in the hero namespace?

**Comment by LoyVanBeek** [comment]
> Did you try the example? For me this works:

It does work locally but not on the robot somehow.

**Comment by reinzor** [comment]
> > Did you try the example? For me this works:
> 
> It does work locally but not on the robot somehow.

debug with `npm run serve` and then `crtl+shift+i` to view the console log messages. Also check whether the connection is established correctly and namespace issues ..

**Comment by LarsJanssenTUe** [comment]
Publishing with the `/hero` namespace makes the difference, but still took some time or something to connect. 

- [x] ```rostopic pub /hero/text_to_speech/output std_msgs/String -- "I am hero, an awesome robot!"```
- [ ] Images

**Comment by LarsJanssenTUe** [comment]
There are however a few feature requests: 
- [x]  Can the text be made bigger?
- [x]  Can the text be in the middle of the screen (like in the vertical sense)?
- [x]  Can the text be displayed longer or until a new line is published?

One more question: currently the /hero/rosbridge_websocket subscribes to the following topics:
```
Subscriptions: 
 * /hero/battery_state/hero1 [sensor_msgs/BatteryState]
 * /hero/battery_state/hero2 [sensor_msgs/BatteryState]
 * /hero/hmi/status [actionlib_msgs/GoalStatusArray]
 * /hero/image_from_ros [sensor_msgs/Image]
 * /hero/runstop_button [std_msgs/Bool]
 * /hero/text_to_speech/output [std_msgs/String]
```  
Shouldn't this also subscribe to the /hero/text_to_speech/input since this is the topic over which the text that hero says is published?

**Comment by reinzor** [comment]
Regarding your feature requests : this can all be done.

Tect apperently is published over the output topic.

**Comment by LoyVanBeek** [comment]
Text output and showing images works too :heavy_check_mark:
