### ISSUE TITLE
Automatically reconnect

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/hero-display#2]
https://github.com/tue-robotics/hero_bringup/pull/26 adds a `systemd-service` to start the display on boot. 
However, if you start a new instance of `hero-start`, the display keeps running but does not reconnect to the new rosbridge-websocket.

Some logging which it is connected to and that it's reconnecting etc would be very very handy.

**Comment by LoyVanBeek** [comment]
@MatthijsBurgh mentioned that e had some code for the auto-reconnecting stuff, but I have no idea how hard this is to do.

**Comment by reinzor** [comment]
It is using the same class as the dashboard. I will look into this why it
is not working

**Comment by reinzor** [comment]
It reconnects but another error popped up:
![image](https://user-images.githubusercontent.com/4176023/60509644-cc0dba00-9d10-11e9-97fb-fca9f5b4bb71.png)

**Comment by MatthijsBurgh** [comment]
Is this error still happening?

**Comment by reinzor** [comment]
I think so

**Comment by MatthijsBurgh** [comment]
This is caused by WS@3.3.3 a dependency of roslib.   I have asked them to use a new version. I forced roslib to use WS@7.2.1 by hacks right now in v0.1.0
